added movie attributes tests and refactor code
MarcoAAlmeida/mb pull request #12
Opened 2023-11-22 22:24 UTC by williamkotesky

2023-11-23 01:25 UTC, MarcoAAlmeida requested changes
Not bad, needs a little work.

2023-11-23 01:25 UTC, MarcoAAlmeida commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +
Essa forma "paralelizada" como escreveu não está errada, mas tbm não favorece o refatoramento

Cheque um filme, depois o outro.

Pra apenas dois filmes, não faz muita diferença.

Mas se vc tiver que repetir isso várias vezes, vai ficar claro que há espaço pra um método

2023-11-23 01:25 UTC, MarcoAAlmeida commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +    	String fileData = Files.readString(Path.of("src/test/resources/omdb/search.json"));
tbm não está errado declarar uma variável intermediária, mas

mockServerClient("s", "Star",Files.readString(Path.of("src/test/resources/omdb/tt0076759.json")))

é mais conciso, 

pergunte-se "vc re-utiliza o conteúdo de fileData em algum lugar?"

2023-11-23 01:25 UTC, MarcoAAlmeida commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +    public void mockingServerClient(String parameterSearch, String parameterMovie, String fileData) {
mockServerClient (sem o gerúndio)

2023-11-23 01:25 UTC, MarcoAAlmeida commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +    public void mockingServerClient(String parameterSearch, String parameterMovie, String fileData) {
pq public?  Alguém mais fora dessa classe usa este método?

2023-11-24 16:51 UTC, MarcoAAlmeida reviewed
Better, just a small correction

2023-11-24 16:51 UTC, MarcoAAlmeida commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +    private void mockServerClient(String parameterSearch, String parameterMovie, String fileData) {
Por favor, mova os métodos privados pro final da classe.

Métodos públicos (tbm conhecidos como "interface da classe") são mais importantes do que os privados.   Há uma boa chance de que um desenvolvedor que estiver lendo não esteja interessado em entrar nos detalhes, então os métodos públicos tem que vir primeiro

2023-11-24 17:00 UTC, williamkotesky commented on src/test/java/br/dev/marcoalmeida/mb/service/MovieServiceTest.java
> +    private void mockServerClient(String parameterSearch, String parameterMovie, String fileData) {
ok!

2023-11-27 18:24 UTC, MarcoAAlmeida commented
Fechando em favor da outra

2023-11-27 18:24 UTC, closed without merging